CREATE OR REPLACE DATABASE COPY_DB;

CREATE OR REPLACE TABLE COPY_DB.PUBLIC.ORDERS(
ORDER_ID STRING,
AMOUNT STRING,
PROFIT INT,
QUANTITY INT,
CATEGORY VARCHAR(30),
SUBCATEGORY VARCHAR(30)
);

CREATE OR REPLACE STAGE COPY_DB.PUBLIC.AWS_STAGE
URL='s3://snowflakebucket-copyoption/returnfailed/';

LIST @COPY_DB.PUBLIC.AWS_STAGE;

COPY INTO COPY_DB.PUBLIC.ORDERS
FROM @COPY_DB.PUBLIC.AWS_STAGE
FILE_FORMAT=(TYPE='CSV', FIELD_DELIMITER=',', SKIP_HEADER=1)
PATTERN='.*Orders.*'
VALIDATION_MODE=RETURN_ERRORS;

COPY INTO COPY_DB.PUBLIC.ORDERS
FROM @COPY_DB.PUBLIC.AWS_STAGE
FILE_FORMAT=(TYPE='CSV' FIELD_DELIMITER=',' SKIP_HEADER=1)
PATTERN='.*Orders.*'
VALIDATION_MODE=RETURN_5_ROWS;

--Assignment
CREATE OR REPLACE TABLE COPY_DB.PUBLIC.EMPLOYEES(
CUSTOMER_ID INT,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
EMAIL VARCHAR(50),
AGE INT,
DEPARTMENT VARCHAR(50)
);

CREATE OR REPLACE STAGE ASS_STAGE
URL='s3://snowflake-assignments-mc/copyoptions/example1';

LIST @ASS_STAGE;

CREATE OR REPLACE FILE FORMAT ASS_FILE
TYPE=CSV FIELD_DELIMITER=','
SKIP_HEADER=1;

LIST @ASS_STAGE;

COPY INTO COPY_DB.PUBLIC.EMPLOYEES
FROM @ASS_STAGE
FILE_FORMAT= (FORMAT_NAME=ASS_FILE)
PATTERN='.*empl.*'
VALIDATION_MODE=RETURN_ERRORS;

COPY INTO COPY_DB.PUBLIC.EMPLOYEES
FROM @ASS_STAGE
FILE_FORMAT= (FORMAT_NAME=ASS_FILE)
PATTERN='.*empl.*'
ON_ERROR=CONTINUE;

LIST @AWS_STAGE;

COPY INTO COPY_DB.PUBLIC.ORDERS
FROM @AWS_STAGE
FILE_FORMAT=(FORMAT_NAME=ASS_FILE)
VALIDATION_MODE=RETURN_ERRORS;

CREATE OR REPLACE TABLE REJECTED AS
SELECT REJECTED_RECORD FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SELECT * FROM REJECTED;

COPY INTO COPY_DB.PUBLIC.ORDERS
FROM @AWS_STAGE
FILE_FORMAT=(FORMAT_NAME=ASS_FILE)
ON_ERROR=CONTINUE;

SELECT * FROM TABLE(VALIDATE(ORDERS,JOB_ID=>'_last'));

SELECT * FROM ORDERS;

SELECT SPLIT_PART(REJECTED_RECORD,',',1) AS ORDER_ID,
SPLIT_PART(REJECTED_RECORD,',',2) AS AMOUNT,
SPLIT_PART(REJECTED_RECORD,',',3) AS PROFIT,
SPLIT_PART(REJECTED_RECORD,',',4) AS QUANTITY,
SPLIT_PART(REJECTED_RECORD,',',5) AS CATEGORY,
SPLIT_PART(REJECTED_RECORD,',',6) AS SUBCATEGORY
FROM REJECTED;
